// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://obkbluzdtskglhpjqakt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9ia2JsdXpkdHNrZ2xocGpxYWt0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzNTE0MzYsImV4cCI6MjA2ODkyNzQzNn0.HupHzLaPNnoBSi1dmddwPL0nA06x63djqmnogEB3eM4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});